### ISSUE TITLE
matlab query datatime type mismatch

### ISSUE THREAD

**Issue by csliuyb** [thulab/iotdb-jdbc#35]

**Comment by csliuyb** [comment]
<img width="189" alt="20171204114545" src="https://user-images.githubusercontent.com/5492877/33535530-0f38b87c-d8e9-11e7-8fa1-08f52b7cf4e6.png">

**Comment by MyXOF** [comment]
已经在https://github.com/thulab/iotdb-jdbc/pull/31/files中解决
