### ISSUE TITLE
iotdb-jdbc未支持getDatabaseProductVersion()

### ISSUE THREAD

**Issue by liuruiyiyang** [thulab/iotdb-jdbc#42]
iotdb-jdbc尚未支持getDatabaseProductVersion()，希望通过getDatabaseProductVersion()获取当前的代码版本，用于iotdb-benchmark的测试对应的代码版本记录

**Comment by MyXOF** [comment]
已经在https://github.com/thulab/iotdb-jdbc/pull/43中解决
